//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerdingViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HerdingViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &lt;OptimizationParameters 
        ///	TurnsOfHerding=&quot;1000&quot; 
        ///	SheepType=&quot;Passive&quot; 
        ///	NumberOfSeenShepherds=&quot;2&quot; 
        ///	NumberOfSeenSheep=&quot;10&quot; 
        ///	SeedForRandomSheepForBest=&quot;1895715163&quot;&gt;
        ///  &lt;PositionsOfShepherds&gt;
        ///    &lt;Vector2D X=&quot;100&quot; Y=&quot;300&quot; /&gt;
        ///    &lt;Vector2D X=&quot;200&quot; Y=&quot;100&quot; /&gt;
        ///    &lt;Vector2D X=&quot;300&quot; Y=&quot;300&quot; /&gt;
        ///  &lt;/PositionsOfShepherds&gt;
        ///  &lt;PositionsOfSheep&gt;
        ///    &lt;Vector2D X=&quot;0&quot; Y=&quot;150&quot; /&gt;
        ///    &lt;Vector2D X=&quot;0&quot; Y=&quot;200&quot; /&gt;
        ///    &lt;Vector2D X=&quot;0&quot; Y=&quot;250&quot; /&gt;
        ///    &lt;Vector2D X=&quot;150&quot; Y=&quot;0&quot; /&gt;
        ///    &lt;Vector2D X=&quot;150&quot; Y=&quot;400&quot; /&gt;
        ///   [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string SampleParameters {
            get {
                return ResourceManager.GetString("SampleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu C:\SheepHerding\Experiments\Nauczone\Wandering20K\Populacja\20200201130307\Best\0.xml
        ///C:\SheepHerding\Experiments\Nauczone\Wandering20K\Populacja\20200201130307\Best\1.xml
        ///C:\SheepHerding\Experiments\Nauczone\Wandering20K\Populacja\20200201130307\Best\2.xml.
        /// </summary>
        internal static string SmapleShepherds {
            get {
                return ResourceManager.GetString("SmapleShepherds", resourceCulture);
            }
        }
    }
}
